-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, p.PRICE * s.SALES_AMOUNT AS SALES
FROM PRODUCT p
JOIN (
    SELECT o.PRODUCT_ID, SUM(o.SALES_AMOUNT) AS SALES_AMOUNT
    FROM OFFLINE_SALE o
    GROUP BY o.PRODUCT_ID
) s ON (p.PRODUCT_ID = s.PRODUCT_ID)
ORDER BY SALES DESC, PRODUCT_CODE ASC