SELECT c.CAR_ID, '대여 가능' AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
WHERE c.CAR_ID NOT IN (
    SELECT c.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
    WHERE c.START_DATE <= '2022-10-16' AND c.END_DATE >= '2022-10-16'
    GROUP BY c.CAR_ID
)

UNION

SELECT c.CAR_ID, '대여중' AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
WHERE c.CAR_ID IN (
    SELECT c.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
    WHERE c.START_DATE <= '2022-10-16' AND c.END_DATE >= '2022-10-16'
    GROUP BY c.CAR_ID
)

ORDER BY CAR_ID DESC