-- 코드를 입력하세요
SELECT FLAVOR
FROM (
    SELECT J_TOTAL_ORDER + TOTAL_ORDER AS TOTAL, f.FLAVOR
    FROM FIRST_HALF f
    JOIN (
        SELECT SUM(j.TOTAL_ORDER) AS J_TOTAL_ORDER, j.FLAVOR
        FROM JULY j
        GROUP BY j.FLAVOR
    ) j ON f.FLAVOR = j.FLAVOR
    ORDER BY TOTAL DESC
    LIMIT 3
) a