-- 코드를 작성해주세요
SELECT
    YEAR(ed.DIFFERENTIATION_DATE) AS YEAR,
    (ms.MAX_SIZE - ed.SIZE_OF_COLONY) AS YEAR_DEV,
    ed.ID AS ID
FROM ECOLI_DATA ed
JOIN (
    SELECT 
    MAX(ed2.SIZE_OF_COLONY) AS MAX_SIZE,
    YEAR(ed2.DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA ed2
    GROUP BY YEAR(ed2.DIFFERENTIATION_DATE)
) ms ON YEAR(ed.DIFFERENTIATION_DATE) = ms.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC