-- 코드를 작성해주세요
SELECT fi2.ID AS ID, fni.FISH_NAME AS FISH_NAME, fi2.LENGTH AS LENGTH
FROM FISH_INFO fi2
JOIN FISH_NAME_INFO fni ON fi2.FISH_TYPE = fni.FISH_TYPE
WHERE fi2.LENGTH IN (
    SELECT MAX(fi.LENGTH)
    FROM FISH_INFO fi
    GROUP BY fi.FISH_TYPE
)
ORDER BY fi2.ID

